export const ErrorMessage = {
  ACCESS_DENIED: 'ACCESS_DENIED',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_DUPLICATE: 'RESOURCE_DUPLICATE',
  INVALID_REQUEST_INPUT: 'INVALID_REQUEST_INPUT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PIP_VALIDATE_FAILED: 'PIP_VALIDATE_FAILED',
  TOO_MANY_REQUEST: 'TOO_MANY_REQUEST',
  LINK_NOT_FOUND: 'LINK_NOT_FOUND',
};
